apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-dev

resources:
  - ../../base

namePrefix: dev-
namespace: dev

commonLabels:
  environment: dev

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - environment=dev
      - debug=true
      - log_level=debug
      - database_url=dev-db.example.com:5432

replicas:
  - name: nginx-app
    count: 2
