apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-staging

resources:
  - ../../base

namePrefix: staging-
namespace: staging

commonLabels:
  environment: staging

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - environment=staging
      - debug=false
      - log_level=warn
      - database_url=staging-db.example.com:5432

replicas:
  - name: nginx-app
    count: 2
