apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.20
          resources:
            requests:
              memory: '128Mi'
              cpu: '500m'
            limits:
              memory: '256Mi'
              cpu: '1000m'
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
