apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-prod

resources:
  - ../../base

namePrefix: prod-
namespace: production

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - environment=production
      - debug=false
      - log_level=error
      - database_url=prod-db.example.com:5432

replicas:
  - name: nginx-app
    count: 3
