apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf
